M48
; DRILL file {KiCad 9.0.3} date 2025-07-13T21:49:15+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-13T21:49:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0126
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0159
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T5C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T7C0.0201
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T8C0.0253
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T9C0.0256
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T10C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T11C0.0320
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T12C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T13C0.0403
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T14C0.0508
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T15C0.0641
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T16C0.0808
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T17C0.1019
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T18C0.1285
%
G90
G05
T1
X6.4807Y-3.826
T2
X5.6142Y-3.8652
T3
X6.528Y-3.826
T4
X5.6484Y-3.8652
T5
X6.5756Y-3.826
T6
X6.6793Y-3.9866
T7
X5.6874Y-3.8652
T8
X5.7311Y-3.8652
T9
X6.6763Y-3.9326
T10
X6.6693Y-3.8696
T11
X5.7803Y-3.8665
T12
X6.6623Y-3.7926
T13
X5.8378Y-3.8652
T14
X5.9063Y-3.8654
T15
X5.9878Y-3.8652
T16
X6.0846Y-3.8652
T17
X6.2016Y-3.8652
T18
X6.3437Y-3.8652
M30
