M48
; DRILL file {KiCad 9.0.3} date 2025-07-15T16:51:32+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-15T16:51:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0126
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0159
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0201
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0253
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0256
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T7C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T8C0.0320
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T9C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T10C0.0403
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T11C0.0508
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T12C0.0641
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T13C0.0808
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T14C0.1019
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T15C0.1285
%
G90
G05
T1
X5.6142Y-3.8652
T2
X5.6484Y-3.8652
T3
X6.6793Y-3.9866
T4
X5.6874Y-3.8652
T5
X5.7311Y-3.8652
T6
X6.6763Y-3.9326
T7
X6.6693Y-3.8696
T8
X5.7803Y-3.8665
T9
X6.6623Y-3.7926
T10
X5.8378Y-3.8652
T11
X5.9063Y-3.8654
T12
X5.9878Y-3.8652
T13
X6.0846Y-3.8652
T14
X6.2016Y-3.8652
T15
X6.3437Y-3.8652
M30
